common:
    arch: resnet34
    workers: 4
    batch_size: 32
    epochs: 100
    policy: "step"
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001
    print_freq: 10
    every_decay: 40
    fl_gamma: 3
model:
    norm_type: frn

