common:
    arch: FeatherNetB
    workers: 10
    batch_size: 256
    epochs: 150
    policy: "step"
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001
    print_freq: 100
    every_decay: 60
    fl_gamma: 3
    mode: RGB
    save_path: checkpoints/feathernetB_bs32-RGB
